### ISSUE TITLE
/examples/api/service/host.go broken.

### ISSUE THREAD

**Issue by spikebike** [protocol/ipfs-examples#15]
I have a working IPFS node, running a daemon, connected to 52 or so other nodes:
$ ipfs swarm peers | wc -l;
52

But if I try to run host.go:
$ wget https://raw.githubusercontent.com/ipfs/examples/master/examples/api/service/host.go
$ go run host.go
panic: resource temporarily unavailable

goroutine 16 [running]:
runtime.panic(0xabe160, 0xb)
    /home/bill/pkg/go-1.3.1/src/pkg/runtime/panic.c:279 +0xf5
main.main()
    /home/bill/src/go/host.go:17 +0x9f

goroutine 19 [finalizer wait]:
runtime.park(0x413a20, 0xf9bf50, 0xf9a1a9)
    /home/bill/pkg/go-1.3.1/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xf9bf50, 0xf9a1a9)
    /home/bill/pkg/go-1.3.1/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /home/bill/pkg/go-1.3.1/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /home/bill/pkg/go-1.3.1/src/pkg/runtime/proc.c:1445

From the README it seems like that should work.

**Comment by jbenet** [comment]
I believe host.go sets up its own ipfs node inside the process. (i.e. it doesnt use another running proc). And because it has the default `~/.ipfs` repo path hardcoded, cant run it simultaneously. try stopping your normal daemon and running host.go.

**Comment by spikebike** [comment]
Ah, sorry, that's obvious now.  I confused "ipfs init # if you haven't already" with "ipfs daemon".  My fault.

It works, and a very useful example at that:
$ go run client.go QmfJegzj2e6R38KP2MYFX2UmCfbvA8h7EavBagqnxgYc3H
I am peer <peer.ID NoDNpu> dialing <peer.ID fJegzj>
Hello! This is whyrusleepings awesome ipfs service

**Comment by jbenet** [comment]
:) :+1:

**Comment by whyrusleeping** [comment]
I should probably update the example with that information.
