### ISSUE TITLE
"Making your own ipfs service" errors

### ISSUE THREAD

**Issue by hackergrrl** [protocol/ipfs-examples#22]
The example references `fsrepo#At`, which doesn't seem to exist. I do however see `fsrepo#Open` consumes a repoPath: https://github.com/ipfs/go-ipfs/blob/master/repo/fsrepo/fsrepo.go#L106

Even with this change though, running the server yields `I am peer: <peer.ID XoPY8C>` but the client balks at `XoPY8C` as input: `panic: multihash length inconsistent: &{4  180 [242 122 13]}`.

(+cc @whyrusleeping from earlier irc conversation in #ipfs)

**Comment by whyrusleeping** [comment]
@noffle `fsrepo.Open` looks to be the right call. And for the peer ID, the printing of that has changed since i wrote this, we will need to print `nd.Identity.Pretty()` to get the full base58 string.

**Comment by whyrusleeping** [comment]
@noffle it looks like the code in the markdown and the code in the directory next to the markdown differ, https://github.com/ipfs/examples/blob/master/examples/api/service/client.go and https://github.com/ipfs/examples/blob/master/examples/api/service/host.go compile and work it seems

**Comment by hackergrrl** [comment]
Yup, you're right. The canonical source works fine. Huzzah!

**Comment by hackergrrl** [comment]
oops; reopening until markdown is fixed to reflect source

**Comment by jbenet** [comment]
@noffle this should be closed now, no?
