### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by jbenet** [protocol/ipfs-examples#3]
make an example that shows how to bootstrap. including:

``` sh
ipfs bootstrap add
ipfs bootstrap rm
ipfs bootstrap list
ipfs bootstrap list >save
ipfs bootstrap rm --all
ipfs bootstrap add --default
ipfs bootstrap rm --all
cat save | ipfs bootstrap add
```

**Comment by insanity54** [comment]
How's this?

# Bootstrap

The IPFS bootstrap list is a list of peers with which the IPFS daemon learns about other peers on the network. IPFS comes with a default list of trusted peers, but you are free to modify the list to suit your needs. One popular use for a custom bootstrap list is to create a personal IPFS network.

List the IPFS bootstrap list

```
> ipfs bootstrap list
/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx
/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLpPVmHKQ4XTPdz8tjDFgdeRFkpV8JgYq8JVJ69RrZm
/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64
/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm
/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3
/ip4/25.196.147.100/tcp/4001/ipfs/QmaMqSwWShsPg2RbredZtoneFjXhim7AQkqbLxib45Lx4S
```

If you understand the risks of adding or removing nodes from this list, you can do so. Here we add a new peer to the bootstrap list.

```
> ipfs add /ip4/25.196.147.100/tcp/4001/ipfs/QmaMqSwWShsPg2RbredZtoneFjXhim7AQkqbLxib45Lx4S
```

Here we remove a node from the bootstrap list

```
> ipfs rm /ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
```

Let's say we want to create a backup of our new bootstrap list. We can easily do this by redirecting stdout of `ipfs bootstrap list` to a file.

```
> ipfs bootstrap list >save
```

If we ever want to start from scratch, we can delete the entire bootstrap list at once.

```
> ipfs bootstrap rm --all
```

With an empty list, we can restore the default bootstrap list

```
> ipfs bootstrap add --default
```

Remove the entire bootstrap list again, and restore our saved one.

```
> ipfs bootstrap rm --all
> cat save | ipfs bootstrap add
```

By [jbenet](http://github.com/jbenet) and [insanity54](http://github.com/insanity54)

**Comment by jbenet** [comment]
@insanity54 this looks good! may want to add it as a file in a PR, so i can make comments inline?

**Comment by insanity54** [comment]
Oh cool, I didn't know you could do inline comments. Created PR.
