### ISSUE TITLE
IPNS example issues

### ISSUE THREAD

**Issue by RichardLitt** [protocol/ipfs-examples#35]
I'm trying to run through [the IPNS example](https://github.com/ipfs/examples/tree/master/examples/ipns).

``` sh
🐕  echo 'Let\'s have some mutable fun!' | ipfs add
-bash: !': event not found
13:37 ~ 🐕  echo 'Let\'s have some mutable fun' | ipfs add
> 
13:38 ~ 🐕  echo "Let's have some mutable fun!" | ipfs add
echo "Let's have some mutable fun" | ipfs add
added QmRnF2MLkznVyV91q7DBPy2AMbbqdCipD8epoNHMtXp8YH QmRnF2MLkznVyV91q7DBPy2AMbbqdCipD8epoNHMtXp8YH
13:38 ~ 🐕  ipfs name publish QmRnF2MLkznVyV91q7DBPy2AMbbqdCipD8epoNHMtXp8YH QmRnF2MLkznVyV91q7DBPy2AMbbqdCipD8epoNHMtXp8YH
Error: keychains not yet implemented
```

The first error is that the exclamation marks don't work on shell. It looks like these were added back in in 477161f43d8abb5d49a15bdebb946a94733cdb51, but I'm not sure why. 

After fixing that manually, I've run against an issue with `keychains not yet implemented`. How do I get around this?

**Comment by daviddias** [comment]
@RichardLitt do `ipfs name publish QmRnF2MLkznVyV91q7DBPy2AMbbqdCipD8epoNHMtXp8YH` only.

The way it works is that it is going to publish using your KeyPair, once you publish once, it will tell you the multihash of your pubkey and then you can do `ipfs name publish <multihash(keypair)> <newHash>' to update the name published. That error is is trying to tell that go-ipfs doesn't implement custom key pairs yet (like, creating several IPNS Records in the same Node, right now there is a limit of 1 per node)

**Comment by RichardLitt** [comment]
@diasdavid thank you! I understand this, now. Got it. :)

**Comment by daviddias** [comment]
rad :D
