### ISSUE TITLE
Mixed imports

### ISSUE THREAD

**Issue by ComSecNinja** [protocol/ipfs-examples#48]
I tried to explain this but it proved nearly impossible to do so in a manner I could even comprehend myself. Hence, an example: 
`github.com/ipfs/go-libp2p/p2p/peer/peer.go` imports `gx/ipfs/.../go-multihash` as `mh` and `gx/ipfs/.../go-ipfs-util` as `u`. In block.go line 22 `Block` expects `gx/ipfs/.../go-multihash.Multihash` but `u.Hash` returns `github.com/jbenet/go-multihash.Multihash`. There are multiple conflicts of this kind out there, of which I list those known to me here:
- github.com/ipfs/go-ipfs/blocks
- github.com/ipfs/go-libp2p/p2p/net/swarm/addr
- github.com/ipfs/go-libp2p/p2p/net/filter
- github.com/ipfs/go-libp2p/p2p/nat
- gx/ipfs/QmSN2ELGRp4T9kjqiSsSNJRUeR9JKXzQEgwe1HH3tdSGbC/go-libp2p/p2p/net/swarm/addr
- github.com/ipfs/go-libp2p/p2p/net/transport
- github.com/ipfs/go-ipfs/thirdparty/testutil

A complete [dump](http://pastebin.com/raw/fxTqewJY) of errors when running `go get` in `examples/api/service`, as per my conversation with @whyrusleeping at freenode#ipfs.

**Comment by ghost** [comment]
Yeah, we need to go through all examples and make sure they're up-to-date and work :(

Closing in favor of #67
