### ISSUE TITLE
examples/api/services out of date

### ISSUE THREAD

**Issue by shazow** [protocol/ipfs-examples#7]
https://github.com/ipfs/examples/tree/master/examples/api/service

The example doesn't build anymore, mostly because packages moved around but possibly some of the API also changed.
- `code.google.com/p/go.net/context` should be `golang.org/x/net/context`
- `github.com/jbenet/go-ipfs/...` should be `github.com/ipfs/go-ipfs/...`
- `~/.go-ipfs` should be `~/.ipfs`

**Comment by shazow** [comment]
Pull request with fixes coming up.

**Comment by whyrusleeping** [comment]
awesome, thank you!
