### ISSUE TITLE
How to keep the IPFS daemon running after logout?

### ISSUE THREAD

**Issue by riyazlafir** [protocol/ipfs-examples#75]
Hi All,

I'm new to ipfs. I want to  know how keep ipfs daemon live when I logout from my testing machine . ipfs daemon running on centos based machine. 
any one please guide me . 

thanks in advance .

**Comment by hsanjuan** [comment]
Hi, create an ipfs system user and use an ipfs service (https://github.com/ipfs/examples/tree/master/examples/init) file to launch IPFS as a regular system service (or follow the guide strictly and launch it as user service).

**Comment by riyazlafir** [comment]
![captured](https://cloud.githubusercontent.com/assets/25414425/24354068/3d2178a0-133c-11e7-852f-ea032dac3a59.PNG)

     but I don't have init folder in my machine do I need to create new init folder or use existing ini.d folder ?
`

**Comment by victorb** [comment]
@riyazlafir depends if you're using Upstart or SysVinit. By default, CentOS is using SusVinit so you should probably go with `/etc/init.d` instead. There is a full example of the service declaration here: https://github.com/dylanPowers/ipfs-linux-service/blob/master/init.d/ipfs
