### ISSUE TITLE
IPNS example - Error: Argument 'path' is required

### ISSUE THREAD

**Issue by dotnetspec** [protocol/ipfs-examples#77]
Win 10 (32 bit)
Git bash
IPFS daemon running

When I try first line of 
https://github.com/ipfs/examples/tree/master/examples/ipns
I get:
echo "Let's have some mutable fun!" | ipfs add
Error: Argument 'path' is required

USAGE
  ipfs add <path>... - Add a file or directory to ipfs.

Path doesn't appear to be specified in the eg.

**Comment by ghost** [comment]
Sorry, these examples are a tiny bit broken -- all of them need to use single quotes and then it should work.

**Comment by ghost** [comment]
Fixed in 809011295e43f4b803445677b9fdd6112e9914be

**Comment by victorb** [comment]
Think that's something else. This: `echo "Let's have some mutable fun!" | ipfs add` should work fine in bash already... zsh will break because of the exclamation though

@dotnetspec Which version of IPFS and which implementation are you using?

**Comment by ghost** [comment]
Weird, exclamation marks for example in `git commit -m "foo!"` never worked for me...

**Comment by dotnetspec** [comment]
ipfs version 0.4.9-rc2
Fairly sure it's a go-ipfs implementation

**Comment by whyrusleeping** [comment]
Stdin input doesnt work on windows. Its disabled because we had so many problems with it behaving inconsistently.

**Comment by JohnKnust** [comment]
is there a workaround to explain the equal hash by adding a file with a custom filename AND stdin directly?

**Comment by victorb** [comment]
I'm not sure I understand you correctly, but you're thinking about the two hashes you get when adding a file from stdin? You could always wrap it in a directory to make the filename visible when `get`ing it. (`QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn` is a empty directory)

```bash
# add file via stdin to ipfs
$ cat package.json | ipfs add
added QmNjCwo5Hd9uVDktPTPDvMDq41tGJJFbRzhGiioPHVynLx QmNjCwo5Hd9uVDktPTPDvMDq41tGJJFbRzhGiioPHVynLx

# add link to empty directory
$ ipfs object patch add-link QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn my-file-package.json QmNjCwo5Hd9uVDktPTPDvMDq41tGJJFbRzhGiioPHVynLx
Qme2L3gFxu4ncV1ougv4atkenTnoVoYKyMcHDmtdGk33Ux

# list links in our new directory
$ ipfs ls Qme2L3gFxu4ncV1ougv4atkenTnoVoYKyMcHDmtdGk33Ux
QmNjCwo5Hd9uVDktPTPDvMDq41tGJJFbRzhGiioPHVynLx 5401 my-file-package.json

# how to traverse our new directory
$ ipfs object stat Qme2L3gFxu4ncV1ougv4atkenTnoVoYKyMcHDmtdGk33Ux/my-file-package.json
NumLinks: 0
BlockSize: 5401
LinksSize: 3
DataSize: 5398
CumulativeSize: 5401
```
