### ISSUE TITLE
when i follow the last example, the command prompt just hangs.. 

### ISSUE THREAD

**Issue by alphaCTzo7G** [protocol/ipfs-examples#81]
I ran the example in https://github.com/ipfs/examples/tree/master/examples/pinning

After I unpinned the file.. and ran ipfs cat, it just hang for ever..

Is it because ipfs is searching for the hash on the network? I was expecting that because its not pinned and the pin has been garbage collected it would return

"cat: foo: No such file or directory"

**Comment by hsanjuan** [comment]
This one's old so I am closing. For anyone looking for support, use https://discuss.ipfs.io.
